[project]
name = "bbb-permeability-gnn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deepchem>=2.8.0",
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "pandas>=3.0.5",
    "qc-b3db>=1.1.1",
    "rdkit>=2026.3.4",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "torch>=2.13.0",
    "torch-geometric>=2.8.0.post1",
]
